### ISSUE TITLE
Is there a CPU version for evaluation only?

### ISSUE THREAD

**Issue by taicaile** [ruotianluo/ImageCaptioning.pytorch#101]
Hi,

I am wondering if you could provide a CPU version for evaluation only.

Thanks.

**Comment by ruotianluo** [comment]
I updated the master.
Try with --device cpu when running eval.py

**Comment by taicaile** [comment]
Hi,

Thanks for your support.

I still couldn't run it, here are step I have tried:

```
# 1, clone the project 
git clone https://github.com/ruotianluo/ImageCaptioning.pytorch
# 2, install
python setup.py install 
# 2, download the resnet101.pth from <https://drive.google.com/drive/folders/0B7fNdx_jAqhtbVYzOURMdDNHSGM>
# and put it into ./data/imagenet_weights
# 3, run eval.py
python tools/eval.py --model model.pth --infos_path infos.pkl --image_folder images  --num_images 1  --device cpu
```
and following error occurred:

```
python tools/eval.py --model model-best.pth --infos_path infos_trans12-best.pkl --image_folder images --num_images 1  --device cpu
Warning: coco-caption not available
Traceback (most recent call last):
  File "tools/eval.py", line 19, in <module>
    import captioning.modules.losses as losses
ModuleNotFoundError: No module named 'captioning.modules'
```

**Comment by ruotianluo** [comment]
run `python -m pip install -e . ` to install this pcakge

**Comment by taicaile** [comment]
> run `python -m pip install -e . ` to install this pcakge

Wow, this works, thanks.

New error occurred as below:

```
python tools/eval.py --model model-best.pth --infos_path infos_trans12-best.pkl --image_folder images  --num_images 1  --device cpu
Warning: coco-caption not available
cider or coco-caption missing
DataLoaderRaw loading images from folder:  images
0
listing all images in directory images
DataLoaderRaw found  4  images
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/mnt/e/github-test/ImageCaptioning.pytorch/captioning/utils/eval_utils.py", line 157, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'labels'
```

**Comment by ruotianluo** [comment]
Because I almost never use dataloaderraw, so I don't maintain dataloaderraw that much. Let me get back to it tomorrow.

**Comment by taicaile** [comment]
Sure, take your time.

By the way, before run the script, I have changed the following code labeled in red box
![image](https://user-images.githubusercontent.com/23215696/87750313-ac6b0600-c82d-11ea-9761-9c8579192635.png)
![image](https://user-images.githubusercontent.com/23215696/87750324-b1c85080-c82d-11ea-805d-6348189e6dd2.png)

And for --model model-best.pth --infos_path infos_trans12-best.pkl files, I downloaded from the links provided in the Colab notebook.
![image](https://user-images.githubusercontent.com/23215696/87750468-197e9b80-c82e-11ea-896b-4b7a2bd53aec.png)

I can run the Colab notebook in my local environment with CPU only. 

Another question is where I can download different detection models and captioning model. Thanks.

**Comment by ruotianluo** [comment]
just let you know. The dataloaderraw only supports resnet101. if you want to use other models, the best choice is to use what's in the colab. For bottomup features, the official code is in caffe, so I don't know if there is any pytorch version that hehaves identitical.

The captioning models are in the MODEL_ZOO.md. Is there a specific model that you want?

**Comment by taicaile** [comment]
I want to test the best performance for Flickr30k dataset.

Thanks.

**Comment by ruotianluo** [comment]
I don't have that for now. Unfortunately.

**Comment by HN123-123** [comment]
I also mat the error:
"DataLoaderRaw found  20 images
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/mnt/e/github-test/ImageCaptioning.pytorch/captioning/utils/eval_utils.py", line 157, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'labels'  "
Did you fix it now?

**Comment by ooza** [comment]
How much time takes the evaluation on a local image? In my case about 30 s and I'm wondering how can we reduce it ??
PS: I'm using the same models as you (the ones of Colab demo)
Thanks
