### ISSUE TITLE
I met a error in the training

### ISSUE THREAD

**Issue by HN123-123** [ruotianluo/ImageCaptioning.pytorch#102]
And when I tried to train on GPU，I met  multiprocessing error as fllow：
“Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train(opt)
  File "train.py", line 231, in train
    infos['loader_state_dict'] = loader.state_dict()
  File "/home1/hu/Pytorch/ImageCaptioning.pytorch-master/captioning/data/dataloader.py", line 363, in state_dict
    for split, loader in self.loaders.items()}
  File "/home1/hu/Pytorch/ImageCaptioning.pytorch-master/captioning/data/dataloader.py", line 363, in <dictcomp>
    for split, loader in self.loaders.items()}
  File "/home1/hu/Pytorch/ImageCaptioning.pytorch-master/captioning/data/dataloader.py", line 359, in get_prefetch_num
    return (self.iters[split]._send_idx - self.iters[split]._rcvd_idx) * self.batch_size
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_send_idx'  ”
How should i fix it？？？

**Comment by ruotianluo** [comment]
what version of pytorch are you using?

**Comment by HN123-123** [comment]
pytorch=1.2.0，torchvision=0.4.0，python=3.6

**Comment by ruotianluo** [comment]
The implementation here only works for pytorch=1.3.0+.

**Comment by HN123-123** [comment]
Firstly，thank you very much for reply.
 I update the version of pytorch to 1.3.1, it can read data now. But when it try to use multi-GPU , mat error as follow:
" Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train(opt)
  File "train.py", line 241, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home1/hu/Pytorch/ImageCaptioning.pytorch-master/captioning/utils/eval_utils.py", line 181, in eval_split
    sents = utils.decode_sequence(model.vocab, seq)
  File "/home1/hu/anaconda3/envs/torch1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'vocab'  "
How can i use customizing functions 'vocab' in 'DataParallel'？？？

**Comment by ruotianluo** [comment]
It's a recently-introduced bug.

**Comment by ruotianluo** [comment]
Let me see how to fix it.

**Comment by ruotianluo** [comment]
try add `dp_model.vocab = getattr(model, 'vocab', None)  # nasty`
under https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/tools/train.py#L86

**Comment by HN123-123** [comment]
Sorry to bother you again.
When I eval use the infos_fc.pkl got from training , it occurs that "eval.py: error: unrecognized arguments: --infos_pth ./log_fc/infos_fc.pkl"

**Comment by HN123-123** [comment]
Sorry to bother you again .
When I run "python tools/eval.py --model model-best.pth --infos_path infos_fc-best.pkl --image_folder images  --num_images 10",   it occured error as  follow:
"DataLoaderRaw loading images from folder:  images 0 listing all images in directory images
DataLoaderRaw found  20  images
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/mnt/e/github-test/ImageCaptioning.pytorch/captioning/utils/eval_utils.py", line 157, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'labels' "
How can i fix it ???
And i also want to know how to use 'DataLoader' to eval the model???

**Comment by ruotianluo** [comment]
1 Try add data['labels'] = np.zeros([batch_size, 0]) after
https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/captioning/data/dataloaderraw.py#L127 

2 Don't input image_folder, then you are using DataLoader.

**Comment by HN123-123** [comment]
When i try to use the Bottom-up features, i mat errors in make_bu_data.py.
"
Traceback (most recent call last):
  File "make_bu_data.py", line 44, in <module>
    item[field] = np.frombuffer(base64.decodestring(item[field]), 
  File "/home1/hu/anaconda3/envs/pytorch_0.4.1/lib/python3.6/base64.py", line 554, in decodestring
    return decodebytes(s)
  File "/home1/hu/anaconda3/envs/pytorch_0.4.1/lib/python3.6/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/home1/hu/anaconda3/envs/pytorch_0.4.1/lib/python3.6/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
"
I try to use "decodebytes" to replace "decodestring" but it mat the error either.
What should i do about it???
