### ISSUE TITLE
KeyError: 'mask'

### ISSUE THREAD

**Issue by AmKhG** [ruotianluo/ImageCaptioning.pytorch#107]
Thanks for the repo, 

It seems that the DataLoaderRaw does not create a 'mask' key in the dataloader dictionary. It fails later on asking for that key. The log is as below:

```
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/XXXXX/captioning/utils/eval_utils.py", line 157, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], **data['masks']**, data['att_masks']]
KeyError: 'masks'
```

Looking at the DataLoaderRaw, lines 126:133 :

```
data = {}
data['fc_feats'] = fc_batch
data['att_feats'] = att_batch.reshape(batch_size, -1, 2048)
data['labels'] = np.zeros([batch_size, 0])
data['att_masks'] = None
data['bounds'] = {'it_pos_now': self.iterator, 'it_max': self.N, 'wrapped': wrapped}
data['infos'] = infos
```
no 'mask' key is created above, could you please have a look?

**Comment by ruotianluo** [comment]
For some reason, I can't push the fix. You can add `data['masks'] = None`
