### ISSUE TITLE
train for flickr30k

### ISSUE THREAD

**Issue by ydyrx-ldm** [ruotianluo/ImageCaptioning.pytorch#134]
您好呀，当我准备flickr30k的数据集的图像特征时，出现了这个错误：
```
Traceback (most recent call last):
  File "scripts/prepro_feats.py", line 101, in <module>
    main(params)
  File "scripts/prepro_feats.py", line 64, in main
    I = skimage.io.imread(os.path.join(params['images_root'], img['filepath'], img['filename']))
KeyError: 'filepath'
```
请问一下您这是什么原因呢？是不是因为flickr30k没分train和val？

**Comment by ydyrx-ldm** [comment]
我的命令是：`python scripts/prepro_feats.py --input_json data/dataset_flickr30k.json --output_dir data/flickr30talk --images_root flickr30k-images`

**Comment by ruotianluo** [comment]
因为默认是使用下载的feature

**Comment by ydyrx-ldm** [comment]
那我想使用Resnet101 的flickr30k怎么操作呢？
好像您提供的文件没有resnet的而只是faster_rcnn生成的特征。

**Comment by ydyrx-ldm** [comment]
你的文件写的操作是：For resnet feature, you can do the same thing as COCO.
我按照文件来就出现这个错误：

> 您好呀，当我准备flickr30k的数据集的图像特征时，出现了这个错误：
> 
> ```
> Traceback (most recent call last):
>   File "scripts/prepro_feats.py", line 101, in <module>
>     main(params)
>   File "scripts/prepro_feats.py", line 64, in main
>     I = skimage.io.imread(os.path.join(params['images_root'], img['filepath'], img['filename']))
> KeyError: 'filepath'
> ```
> 
> 请问一下您这是什么原因呢？是不是因为flickr30k没分train和val？

**Comment by ruotianluo** [comment]
你debug进去看看是有什么不一样

**Comment by ruotianluo** [comment]
他只是里面没有filepath，img里面应该有类似的entry。应该不超过两行的修改吧

**Comment by ydyrx-ldm** [comment]
好的，待会看看

**Comment by ydyrx-ldm** [comment]
好的，待会看看

**Comment by ydyrx-ldm** [comment]
您好，当我进行flickr30k训练时出现以下错误：
Traceback (most recent call last):
  File "tools/train.py", line 296, in <module>
    train(opt)
  File "tools/train.py", line 250, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/ImageCaptioning.pytorch/captioning/utils/eval_utils.py", line 207, in eval_split
    predictions.pop()
IndexError: pop from empty list
请问一下怎么解决呢？

**Comment by zzx-jim** [comment]
> 更改 --save_checkpoint_every 6000 和 --val_images_use 5000 小。



> 我的命令是：`python scripts/prepro_feats.py --input_json data/dataset_flickr30k.json --output_dir data/flickr30talk --images_root flickr30k-images`

How to get dataset_flickr30k.json

**Comment by zzx-jim** [comment]
> 您好呀，当我准备flickr30k的数据集的图像特征时，出现了这个错误：
> 
> ```
> Traceback (most recent call last):
>   File "scripts/prepro_feats.py", line 101, in <module>
>     main(params)
>   File "scripts/prepro_feats.py", line 64, in main
>     I = skimage.io.imread(os.path.join(params['images_root'], img['filepath'], img['filename']))
> KeyError: 'filepath'
> ```
> 
> 请问一下您这是什么原因呢？是不是因为flickr30k没分train和val？

请问我也遇到同样的问题，怎么解决呢？

**Comment by ydyrx-ldm** [comment]
> 

他只是里面没有filepath，img里面应该有类似的entry。应该不超过两行的修改吧

**Comment by ydyrx-ldm** [comment]
@zzx-jim 他只是里面没有filepath，img里面应该有类似的entry。应该不超过两行的修改吧
