### ISSUE TITLE
error when eval

### ISSUE THREAD

**Issue by ydyrx-ldm** [ruotianluo/ImageCaptioning.pytorch#135]
您好，我新环境进行eval时出现了这个问题，请问是哪一步出现问题了，我没安装那个包呢？谢谢您。
Traceback (most recent call last):
  File "tools/eval.py", line 74, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/yuanling/final_work/ImageCaptioning.pytorch/captioning/utils/eval_utils.py", line 85, in language_eval
    cocoEval = COCOEvalCap(coco, cocoRes)
NameError: name 'COCOEvalCap' is not defined

**Comment by ruotianluo** [comment]
coco-caption没有装好？

**Comment by ydyrx-ldm** [comment]
重新装了，还是不行。
我只好用回原来的系统进行eval。
新环境就出现上述错误。

**Comment by ydyrx-ldm** [comment]
我有个问题就是：比如我eval了一次这个best-model后，再次换一个新的best-model进行eval时，得到的是上一次eval的结果。
我把eval_results 的文件删除也是上一次的结果。
这是什么情况呢？是生成的结果缓存吗？有什么方法可以每次都eval新的model呢？

**Comment by ruotianluo** [comment]
eval的时候加上--force

Ruotian Luo

**Comment by ydyrx-ldm** [comment]
成功了，thanks
