### ISSUE TITLE
RuntimeError: gather(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by gcj2021** [ruotianluo/ImageCaptioning.pytorch#142]
抱歉再一次打扰你了
我按照步骤训练coco数据集的时候，报了这个错
您有解决思路吗？

DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotalk_fc data/cocotalk_att data/cocotalk_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Read data: 0.2834451198577881
Save ckpt on exception ...
model saved to ./log_fc\model.pth
Save ckpt done.
Traceback (most recent call last):
  File "tools/train.py", line 185, in train
    model_out = dp_lw_model(fc_feats, att_feats, labels, masks, att_masks, data['gts'], torch.arange(0, len(data['gts'])), sc_flag, struc_flag, drop_worst_flag)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\pytorch-imagecaptioning\the2time\captioning\modules\loss_wrapper.py", line 47, in forward
    loss = self.crit(self.model(fc_feats, att_feats, labels[..., :-1], att_masks), labels[..., 1:], masks[..., 1:], reduction=reduction)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\pytorch-imagecaptioning\the2time\captioning\modules\losses.py", line 193, in forward
    output = -input.gather(2, target.unsqueeze(2)).squeeze(2) * mask
RuntimeError: gather(): Expected dtype int64 for index

**Comment by gcj2021** [comment]
对了，您训练用的pytorch版本是？我认为可能和torch版本有关

**Comment by ruotianluo** [comment]
我最近用的是1.8

**Comment by gcj2021** [comment]
解决啦。target.unsqueeze(2)的dtype是int32类型的，我把它转为int64了，已经可以运行了，谢谢
