### ISSUE TITLE
a RuntimeError when I'm training

### ISSUE THREAD

**Issue by gcj2021** [ruotianluo/ImageCaptioning.pytorch#143]
训练到这里出现了一个问题
.......
iter 56643 (epoch 4), train_loss = 2.471, time/batch = 0.056
Read data: 0.005997896194458008
Save ckpt on exception ...
model saved to ./log_fc\model.pth
Save ckpt done.
Traceback (most recent call last):
  File "tools/train.py", line 185, in train
    model_out = dp_lw_model(fc_feats, att_feats, labels, masks, att_masks, data['gts'], torch.arange(0, len(data['gts'])), sc_flag, struc_flag, drop_worst_fl
ag)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\pytorch-imagecaptioning\the2time\captioning\modules\loss_wrapper.py", line 47, in forward
    loss = self.crit(self.model(fc_feats, att_feats, labels[..., :-1], att_masks), labels[..., 1:], masks[..., 1:], reduction=reduction)
  File "E:\Anaconda\envs\ImageCaptioning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\pytorch-imagecaptioning\the2time\captioning\models\CaptionModel.py", line 33, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "e:\pytorch-imagecaptioning\the2time\captioning\models\AttModel.py", line 157, in _forward
    it.index_copy_(0, sample_ind, torch.multinomial(prob_prev, 1).view(-1).index_select(0, sample_ind))
RuntimeError: index_copy_(): self and source expected to have the same dtype, but got (self) Int and (source) Long

请问为什么会出现这种情况，大致出错原因但是不知道如何改，在之前的训练过程中一直没问题，为什么到iter 56643 (epoch 4) 这里
Read data: 0.005997896194458008后报错了呢？搞了好久都没有解决，只能来求助你了，多谢

**Comment by geass0127** [comment]
麻烦请问一下你解决了这个问题吗，我也遇到这个问题了

**Comment by gcj2021** [comment]
> 麻烦请问一下你解决了这个问题吗，我也遇到这个问题了

解决了，修改一下数据类型就行，我现在在外地，我回去把修改的代码发到这儿

**Comment by violet2274** [comment]
请问，这个问题需要修改哪里的代码

**Comment by violet2274** [comment]
请问，这个问题该怎么解决

**Comment by buyongbaoqian** [comment]
你好，我也遇到这个问题了，可以提示一下怎么解决吗，谢谢

**Comment by clear230114** [comment]
@buyongbaoqian 可以把AttModel.py大概一百五十多行的代码换成下面这样就可以跑了 it.index_copy_(0, sample_ind, torch.multinomial(prob_prev, 1).view(-1).index_select(0, sample_ind).int())
