### ISSUE TITLE
测试的时候遇到bug

### ISSUE THREAD

**Issue by zhouhaonan011** [ruotianluo/ImageCaptioning.pytorch#144]
Warning: coco-caption not available
DataLoaderRaw loading images from folder:  blah
0
listing all images in directory blah
DataLoaderRaw found  134  images
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "D:\ResNet152\captioning\utils\eval_utils.py", line 168, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'labels'

一直在报错，在Ubuntu和windows里都是这样，麻烦您帮我看看

**Comment by ruotianluo** [comment]
你设置--language_eval 0。

**Comment by zhouhaonan011** [comment]
> 你设置--language_eval 0。

bug消失了，谢谢您的帮助
