### ISSUE TITLE
failed to generate and save fc and att features to .h5 files, for my own datasets

### ISSUE THREAD

**Issue by SkylerZheng** [ruotianluo/ImageCaptioning.pytorch#57]
processing 0/279 (0.00% done)
Traceback (most recent call last):
  File "/home/jzheng/PycharmProjects/ImageCaptioning_Skyler/scripts/prepro_feats_sky.py", line 119, in <module>
    main(params)
  File "/home/jzheng/PycharmProjects/ImageCaptioning_Skyler/scripts/prepro_feats_sky.py", line 89, in main
    (2048,), dtype="float")
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 119, in create_dataset
    self[name] = dset
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 287, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)

**Comment by SkylerZheng** [comment]
problem solved

**Comment by SkylerZheng** [comment]
you just need to delete the old folders
