### ISSUE TITLE
I got an error during training process

### ISSUE THREAD

**Issue by fearless77** [ruotianluo/ImageCaptioning.pytorch#58]
When I run train.py, I got the error as follows ：

/usr/bin/python2.7 /home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/train.py --id st --caption_model show_tell --input_json data/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_st --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 25 --language_eval 1
Tensorflow not installed; No tensorboard logging.
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotalk_fc data/cocotalk_att data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Read data: 0.282783985138
/home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/models/ShowTellModel.py:79: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.log_softmax(self.logit(self.dropout(output.squeeze(0))))
iter 0 (epoch 0), train_loss = 9.165, time/batch = 0.175
Read data: 0.00908994674683
iter 1 (epoch 0), train_loss = 9.113, time/batch = 0.032
Read data: 0.00635409355164
iter 2 (epoch 0), train_loss = 9.063, time/batch = 0.034
Read data: 0.00556612014771
... ...

image 451949: a man in a suit and tie holding a tennis racket
image 203138: a man in a suit and tie holding a cell phone
image 296759: a dog is laying on a bed with a stuffed animal
evaluating validation preformance... -1/5000 (2.630593)
loading annotations into memory...
0:00:00.502267
creating index...
index created!
using 5000/5000 predictions
Loading and preparing results...     
DONE (t=0.04s)
creating index...
Traceback (most recent call last):
  File "/home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/train.py", line 204, in <module>
    train(opt)
  File "/home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/train.py", line 147, in train
    val_loss, predictions, lang_stats = eval_utils.eval_split(model, crit, loader, eval_kwargs)
  File "/home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/eval_utils.py", line 139, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/vipsl422-2/Desktop/ImageCaptioning.pytorch-master/eval_utils.py", line 45, in language_eval
    cocoEval = COCOEvalCap(coco, cocoRes)
TypeError: __init__() takes exactly 4 arguments (3 given)
index created!
Terminating BlobFetcher

I have already set  --language_eval 1，but I don't know why I got this error.
I need your help, sorry to bother you.

**Comment by fearless77** [comment]
I don't download the correct folder and documents.
Now I can run this successfully! Sorry to bother!
