### ISSUE TITLE
TypeError: h5py objects cannot be pickled

### ISSUE THREAD

**Issue by Tuckdu** [ruotianluo/ImageCaptioning.pytorch#99]
Hi,

I try to run the train.py script but I've got this:

<pre> C:\Users\tlepen\Documents\ImageCaptioning.pytorch>python tools/train.py --cfg configs/fc.yml --id fc
Warning: coco-caption not available
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotalk_fc data/cocotalk_att data/cocotalk_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "tools/train.py", line 287, in <module>
    train(opt)
  File "tools/train.py", line 37, in train
    loader = DataLoader(opt)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\captioning-0.0.1-py3.7.egg\captioning\data\dataloader.py", line 322, in __init__
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\h5py\_hl\base.py", line 308, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled</pre>

Do you have any solution ?
Thanks for your help.

**Comment by ruotianluo** [comment]
I have never met this problem:

Try this:
```

            self.h5_label_file = h5py.File(self.opt.input_label_h5, 'r', driver='core')
            # load in the sequence data
            seq_size = self.h5_label_file['labels'].shape
            self.label = self.h5_label_file['labels'][:]
            self.seq_length = seq_size[1]
            print('max sequence length in data is', self.seq_length)
            # load the pointers in full to RAM (should be small enough)
            self.label_start_ix = self.h5_label_file['label_start_ix'][:]
            self.label_end_ix = self.h5_label_file['label_end_ix'][:]
```
->
```

            h5_label_file = h5py.File(self.opt.input_label_h5, 'r', driver='core')
            # load in the sequence data
            seq_size = h5_label_file['labels'].shape
            self.label = h5_label_file['labels'][:]
            self.seq_length = seq_size[1]
            print('max sequence length in data is', self.seq_length)
            # load the pointers in full to RAM (should be small enough)
            self.label_start_ix = h5_label_file['label_start_ix'][:]
            self.label_end_ix = h5_label_file['label_end_ix'][:]
```

**Comment by Tuckdu** [comment]
I tried and I have this error now:
<pre>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tlepen\Documents\ImageCaptioning.pytorch\tools\train.py", line 287, in <module>
    train(opt)
  File "C:\Users\tlepen\Documents\ImageCaptioning.pytorch\tools\train.py", line 37, in train
    loader = DataLoader(opt)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\captioning-0.0.1-py3.7.egg\captioning\data\dataloader.py", line 322, in __init__
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File ".\tools\train.py", line 287, in <module>
    train(opt)
  File ".\tools\train.py", line 37, in train
    loader = DataLoader(opt)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\captioning-0.0.1-py3.7.egg\captioning\data\dataloader.py", line 322, in __init__
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe</pre>

**Comment by ruotianluo** [comment]
It may be a windows problem. I'm not sure. I definitely haven't seen it before either

**Comment by gcj2021** [comment]
> I tried and I have this error now:
> 
> Traceback (most recent call last):
>   File "", line 1, in 
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\tlepen\Documents\ImageCaptioning.pytorch\tools\train.py", line 287, in 
>     train(opt)
>   File "C:\Users\tlepen\Documents\ImageCaptioning.pytorch\tools\train.py", line 37, in train
>     loader = DataLoader(opt)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\captioning-0.0.1-py3.7.egg\captioning\data\dataloader.py", line 322, in __init__
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
>     w.start()
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> Traceback (most recent call last):
>   File ".\tools\train.py", line 287, in 
>     train(opt)
>   File ".\tools\train.py", line 37, in train
>     loader = DataLoader(opt)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\captioning-0.0.1-py3.7.egg\captioning\data\dataloader.py", line 322, in __init__
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
>     w.start()
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\tlepen\AppData\Local\Continuum\anaconda3\envs\captioning\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> BrokenPipeError: [Errno 32] Broken pipe

try this:
find ./captioning/data/dataloader.py  line321   
change the "num_workers" to 0
may solve your problem
